### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by nomadism19** [gauravsuman007/megabasterd-docker#2]
Hi, your latest update causes the container to crash upon startup.

```shell
2023-06-23T20:17:21.160492113Z [app] starting MegaBasterd...
2023-06-23T20:17:21.164890285Z [services.d] done.
2023-06-23T20:17:21.859075913Z Jun 23, 2023 1:17:21 PM com.tonikelope.megabasterd.SqliteSingleton getConn
2023-06-23T20:17:21.859115576Z SEVERE: path to '/dev/null/.megabasterd7.74/megabasterd.db': '/dev/null/.megabasterd7.74' does not exist
2023-06-23T20:17:21.859838980Z Exception in thread "main" java.lang.NullPointerException
2023-06-23T20:17:21.859861152Z 	at com.tonikelope.megabasterd.DBTools.setupSqliteTables(DBTools.java:33)
2023-06-23T20:17:21.859869467Z 	at com.tonikelope.megabasterd.MainPanel.<init>(MainPanel.java:258)
2023-06-23T20:17:21.859876597Z 	at com.tonikelope.megabasterd.MainPanel.main(MainPanel.java:136)
2023-06-23T20:17:22.025476057Z [services.d] stopping services
2023-06-23T20:17:22.247550465Z [services.d] stopping app...
2023-06-23T20:17:22.254897561Z [services.d] stopping logmonitor...
2023-06-23T20:17:22.256362348Z [services.d] stopping openbox...
2023-06-23T20:17:22.267450531Z [services.d] stopping statusmonitor...
2023-06-23T20:17:22.270114147Z [services.d] stopping x11vnc...
2023-06-23T20:17:22.272322819Z caught signal: 15
2023-06-23T20:17:22.272880834Z 23/06/2023 13:17:22 deleted 40 tile_row polling images.
2023-06-23T20:17:22.276417892Z [services.d] stopping nginx...
2023-06-23T20:17:22.286016418Z [services.d] stopping certsmonitor...
2023-06-23T20:17:22.288419600Z [services.d] stopping xvfb...
2023-06-23T20:17:22.322111666Z [services.d] stopping s6-fdholderd...
2023-06-23T20:17:22.340631064Z [cont-finish.d] executing container finish scripts...
2023-06-23T20:17:22.342915924Z [cont-finish.d] done.
2023-06-23T20:17:22.343503868Z [s6-finish] syncing disks.
2023-06-23T20:17:22.347976191Z [s6-finish] sending all processes the TERM signal.
2023-06-23T20:17:25.355575209Z [s6-finish] sending all processes the KILL signal and exiting.
2023-06-23T20:18:25.925674131Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2023-06-23T20:18:26.024778454Z [s6-init] ensuring user provided files have correct perms...exited 0.
2023-06-23T20:18:26.028531910Z [fix-attrs.d] applying ownership & permissions fixes...
2023-06-23T20:18:26.031656774Z [fix-attrs.d] done.

```

**Comment by gauravsuman007** [comment]
Thanks for reporting this. I changed the java version used and the way the jar is deployed to also support arm64 devices.

The build is working fine on my arm64 machine and I no longer have an Intel/amd machine for testing.

I will recommend to pull the docket image with tag 1.0 for now as I won't be able to debug it this weekend.

I will respond here as soon as I've debugged this and you can test the new build and give me feedback.

**Comment by tekwarfare** [comment]
I am having the same issue (on Unraid with Intel x64 processor)
Changing repository to: "gauravsuman007/megabasterd:1.0" has installed the 9-month old version (7.55) but it's working now

**Comment by gauravsuman007** [comment]
I have updated the images and it's working on my arm64 machine. Can someone check on intel machine and report if the latest image works?

**Comment by gauravsuman007** [comment]
> I am having the same issue (on Unraid with Intel x64 processor) Changing repository to: "gauravsuman007/megabasterd:1.0" has installed the 9-month old version (7.55) but it's working now

Please try the updated image and report back. I've also updated the Megabasterd version to 7.74

**Comment by userforusing** [comment]
Works again on my synology ds 720 with Intel CPU . Thank you.

**Comment by tekwarfare** [comment]
~~Changed repository back to "gauravsuman007/megabasterd" and it's crashing at startup same as before. Here is the docker log:~~

Edit: removed docker image , deleted appdata folder and re-installed. Seems to be working and running the latest 7.74 now :)

**Comment by gauravsuman007** [comment]
Glad it's also working for you, closing the issue now
